/* DOM integration tests; no browser rendering is claimed. npm install && npm test */
const {JSDOM}=require('jsdom');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../dist');
(async()=>{
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 const dom=new JSDOM(html,{url:'https://buscaem.test/',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window;
 w.fetch=async url=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(path.join(root,url),'utf8'))});
 w.HTMLElement.prototype.scrollIntoView=function(){};
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
 w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};
 w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
 let downloads=0;w.HTMLAnchorElement.prototype.click=function(){if(this.download)downloads++};
 await w.eval('(async()=>{'+fs.readFileSync(path.join(root,'app.js'),'utf8')+'})()');
 const q=s=>w.document.querySelector(s);
 const all=s=>[...w.document.querySelectorAll(s)];
 const tick=()=>new Promise(r=>setTimeout(r,20));
 assert.equal(all('[data-field="keyword"], [data-field="language"]').length,0);
 assert.equal(all('#articles .article').length,10);
 assert.ok(q('#results-count').textContent.includes('resultados'));
 q('#next').click();assert.match(q('#pagination').textContent,/Página 2/);
 q('#prev').click();assert.match(q('#pagination').textContent,/Página 1/);
 const checkbox=q('[data-field="journal"]');checkbox.checked=true;checkbox.dispatchEvent(new w.Event('change'));
 assert.equal(new Set(all('.article-top a').map(a=>a.textContent)).size,1);
 q('#clear').click();
 q('#query').value='probabilidade';q('.search').dispatchEvent(new w.Event('submit',{cancelable:true}));
 assert.ok(all('#articles .article').length>0);
 q('#sort').value='oldest';q('#sort').dispatchEvent(new w.Event('change'));
 const years=all('.article-year').map(x=>Number(x.textContent));assert.deepEqual(years,[...years].sort((a,b)=>a-b));
 q('.article h3 a').dispatchEvent(new w.MouseEvent('click',{bubbles:true,cancelable:true}));await tick();
 assert.equal(q('#record-dialog').open,true);assert.ok(q('#record-title').textContent);
 q('#ris').click();q('#bib').click();q('#csv').click();assert.equal(downloads,3);
 q('.close').click();assert.equal(q('#record-dialog').open,false);
 q('#query').value='zzzinexistente999';q('.search').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.match(q('#articles').textContent,/Nenhum/);
 q('#reset-search').click();assert.equal(all('#articles .article').length,10);
 w.location.hash='#revistas';await tick();assert.ok(q('[data-journal]'));
 q('[data-journal]').click();await tick();assert.equal(all('[data-field="journal"]:checked').length,1);
 w.location.hash='#dados';await tick();assert.ok(q('table'));assert.match(q('table').textContent,/Coleta/);
 w.location.hash='#sobre';await tick();assert.match(q('main').textContent,/Não são feitas traduções/);
 dom.window.close();console.log('OK: busca, paginação, revista, ordenação, registro, exportações, estado vazio e navegação.');
})().catch(e=>{console.error(e);process.exitCode=1});
